//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AO3SchedulerWin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AO3SchedulerWin.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///CREATE TABLE IF NOT EXISTS &quot;STORY_UPDATES&quot; (
        ///	&quot;id&quot;	INTEGER UNIQUE,
        ///	&quot;authorId&quot;	INTEGER,
        ///	&quot;storyId&quot;	INTEGER,
        ///	&quot;title&quot;	TEXT,
        ///	&quot;chapterTitle&quot;	TEXT,
        ///	&quot;publishingDate&quot;	TEXT,
        ///	&quot;chapterSummary&quot;	TEXT,
        ///	&quot;chapterNotes&quot;	TEXT,
        ///	&quot;notesAtTheStart&quot;	NUMERIC DEFAULT 0,
        ///	&quot;notesAtTheEnd&quot;	NUMERIC DEFAULT 0,
        ///	&quot;storyContent&quot;	TEXT,
        ///	PRIMARY KEY(&quot;id&quot; AUTOINCREMENT),
        ///	FOREIGN KEY(&quot;authorId&quot;) REFERENCES &quot;AUTHORS&quot;(&quot;id&quot;) ON DELETE RESTRICT
        ///);
        ///CREATE TABLE IF NOT EXISTS &quot;LOCAL_SETTINGS&quot; (
        ///	&quot;loggedUse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbCreationScript {
            get {
                return ResourceManager.GetString("DbCreationScript", resourceCulture);
            }
        }
    }
}
